spring.application.name=HeThongPhanLuongBenhVien
# Cấu hình kết nối Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=29061612

# Cấu hình Hibernate / JPA (Tự động cập nhật bảng hoặc sinh SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081